services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=kernel-logs
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - stock-ms-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs/logs.log:/usr/share/logstash/data/logs.log
      - ./logs:/usr/share/logstash/logs
    networks:
      - stock-ms-net
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment: # Définit l'URL Elasticsearch et les options Node.js pour le conteneur Kibana.
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - 'NODE_OPTIONS=--max-old-space-size=2048'
    networks:
      - stock-ms-net
    depends_on:
      - elasticsearch

  stock-ms-app:
    container_name: stock-ms-app
    image: registry.gitlab.com/isi-dev/microservices/stock-ms
    ports:
      - "8081:8081"
    networks:
      - stock-ms-net
    depends_on:
      - logstash
networks:
  stock-ms-net:
    driver: bridge

volumes:
  esdata:
    driver: local